- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.bulit.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo
  - name: install mongodb
    ansible.bulit.package:
     name: mongodb-org
     state: present
  - name: start and enable mongod
    ansible.builtin.service:
     name: mongodb
     state: started
     enabled: yes
  - name: edit file
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'
  - name: restart mongodb
    ansible.builtin.service:
     name: mongod
     state: restarted
  
